spring:
  application:
    name: backend
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
ml-service:
  base-url: ${ML_SERVICE_BASE_URL:http://localhost:8000}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n"
